# Generated by Django 5.1.4 on 2025-07-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient_detials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=7)),
                ('mail', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=35)),
                ('Address', models.CharField(max_length=60)),
                ('Mobile_Number', models.IntegerField()),
            ],
        ),
    ]
