# Generated by Django 5.1.4 on 2025-07-19 07:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiagnoseAI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_detials',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
