# Generated by Django 5.1.4 on 2025-07-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiagnoseAI', '0002_patient_detials_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='cardiac_arrest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=35)),
                ('age', models.IntegerField()),
                ('Sex', models.CharField(max_length=7)),
                ('Chestpaintype', models.CharField(max_length=5)),
                ('RestingBP', models.IntegerField()),
                ('Cholestrol', models.IntegerField()),
                ('FastingBP', models.IntegerField()),
                ('RestingECG', models.CharField(max_length=35)),
                ('MAXHR', models.IntegerField()),
                ('Excersice_angina', models.CharField(max_length=7)),
                ('oldpeak', models.IntegerField()),
                ('STslope', models.CharField(max_length=83)),
            ],
        ),
    ]
