# Generated by Django 5.1.4 on 2025-07-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiagnoseAI', '0004_cardiac_arrest_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='diabetics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=150)),
                ('sex', models.CharField(max_length=21)),
                ('pregnanicies', models.IntegerField()),
                ('glucose', models.IntegerField()),
                ('bp', models.IntegerField()),
                ('skinthickness', models.IntegerField()),
                ('insulin', models.IntegerField()),
                ('bmi', models.DecimalField(decimal_places=5, max_digits=9)),
                ('diabetespedigreefunction', models.DecimalField(decimal_places=5, max_digits=9)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
