# Generated by Django 5.1.4 on 2025-07-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiagnoseAI', '0006_remove_diabetics_sex_diabetics_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='stroke_pred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=31)),
                ('hypertension', models.IntegerField()),
                ('heartdisease', models.IntegerField()),
                ('evermarried', models.CharField(max_length=32)),
                ('worktype', models.CharField(max_length=35)),
                ('residencetype', models.CharField(max_length=34)),
                ('averageglucoselevel', models.IntegerField()),
                ('bmi', models.DecimalField(decimal_places=4, max_digits=6)),
                ('smokingstatus', models.CharField(max_length=31)),
                ('stroke_result', models.CharField(max_length=22)),
            ],
        ),
    ]
