# Generated by Django 5.1.4 on 2025-08-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiagnoseAI', '0007_stroke_pred'),
    ]

    operations = [
        migrations.CreateModel(
            name='anemia_hemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('gender', models.IntegerField()),
                ('hemo', models.IntegerField()),
                ('mch', models.IntegerField()),
                ('mchc', models.IntegerField()),
                ('mcv', models.IntegerField()),
            ],
        ),
    ]
